version: "3.9"

services:
  localhost:
    container_name: localhost
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: digitachief
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  digital-chief-service:
    image: yashbba/digital-chief
    restart: unless-stopped
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3307
    depends_on:
      - localhost
    ports:
      - "8080:8080"
 

